### ISSUE TITLE
'Filter by Name' textbox appearing on 'Survey Summary' page

### ISSUE THREAD

**Issue by ZacharyWallace** [ChromeTemplar/nhlakes_unhm#26]
The 'Filter by Name' textbox is appearing on the 'Survey Summary' page despite there being no name column to filter by.

![image](https://cloud.githubusercontent.com/assets/15005623/10622570/6ec47886-7756-11e5-8afa-2092371ff917.png)

**Comment by kitala1** [comment]
Fixed in 378.
