### ISSUE TITLE
Survey Summary does not validate totals

### ISSUE THREAD

**Issue by ChromeTemplar** [ChromeTemplar/nhlakes_unhm#34]
Steps to recreate:
1) log in as a Lake Host
2) Click on the "new" survey Summary button
3) For the "Number Inspected" type in 14
4) For all other numbers, enter in combinations that add up 13
5) Save the survey -- no validation errors occur

**Comment by swaggermeister** [comment]
May be removing the "total inspected" field depending on direction from Andrea, as field is redundant. In meantime, this is fixed in rev 367.
