### ISSUE TITLE
Survey Summary: The totals are incorrect

### ISSUE THREAD

**Issue by ChromeTemplar** [ChromeTemplar/nhlakes_unhm#38]
Steps to reproduce:

1) enter in the survey summary -- specify that 14 inspections took place
2) click on "all" for the Survey Summary
3) The totals for the group are 1 higher than before, not 14 higher

**Comment by swaggermeister** [comment]
Corrected in 371. Query had pulled count of rows in surveysummary table...not a sum of inspections in all rows.
