### ISSUE TITLE
Query to validate user on login has typo

### ISSUE THREAD

**Issue by swaggermeister** [ChromeTemplar/nhlakes_unhm#6]
nhlakes_unhm/php/model/loginnhvbsrmodel.php, line 23. Select from user should be select from User.

**Comment by swaggermeister** [comment]
Actually this seems to be a bit more widespread, everywhere the user table is referenced is an issue. Maybe the default on windows is non-case-sensitive for mysql?

**Comment by gricklegrass** [comment]
The default for all of SQL is case insensitive, but Claire fixed it anyways.
