### ISSUE TITLE
No way to edit Lake Host Users

### ISSUE THREAD

**Issue by mgw1992** [ChromeTemplar/nhlakes_unhm#8]
I found out there's no way to edit lake host users.  I think this would be helpful if the same lake host doesn't come back after a year or two.

**Comment by ZacharyWallace** [comment]
Lake Hosts are editable. Specifically they can be Deactivated and Activated.

![image](https://cloud.githubusercontent.com/assets/15005623/11519860/8438542c-986b-11e5-9348-e9f1c3953891.png)
